modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CoolAid48/Village-Pillage-Tweaks/issues"
license = "MIT"

[[mods]]
modId = "villagepillagetweaks"
version = "${version}"
displayName = "Village and Pillage Tweaks"
authors = "CoolAid48"
credits = "PurpleSquirrel1503 (Mod icon)"
description = '''
A collection of server-side villager/pillager-related tweaks
'''

logoFile = "assets/villagepillagetweaks/icon.png"

[[mixins]]
config = "villagepillagetweaks.mixins.json"
